### ISSUE TITLE
下载失败，闪退（已处理，待测试）

### ISSUE THREAD

**Issue by hz0324** [hz0324/NeatReaderBugReport#10]
bug反馈：手机端点击下载云端图书后应用闪退，再打开，仍然没有下载成功
机型：小米mix2 MIUI10（安卓8.0.0）

**Comment by zjusutao** [comment]
同，只成功下载了一本，之后下载都会闪退
一加6，安卓9.0

**Comment by hz0324** [comment]
@hellcan 你得处理一下

**Comment by hellcan** [comment]
处理完成
