### ISSUE TITLE
下载云端图书app闪退

### ISSUE THREAD

**Issue by homgwu** [hz0324/NeatReaderBugReport#11]
如题目，小米红米NOTE4X-android7.0

**Comment by hz0324** [comment]
@homgwu 多谢

**Comment by homgwu** [comment]
> @homgwu 多谢

从右上角更多进入云端存储，再下载可以复现。

**Comment by hz0324** [comment]
合并 issue 
https://github.com/hz0324/NeatReaderBugReport/issues
