### ISSUE TITLE
多端同步问题

### ISSUE THREAD

**Issue by yechtop** [hz0324/NeatReaderBugReport#18]
复现步骤：
1.手机上浏览完后，关闭软件
2.打开电脑端Neat reader，发现仍然是之前在电脑端访问的记录
3.再次访问手机端，发现出现了两个一模一样的书
4.再次测试发现后来出现的那本书可以实现多端同步功能

机型：红米5plus，android7.1.2，MIUI10.1
电脑：64位，win10
neat版本：3.1.3
令：建议添加打开图片功能

**Comment by hz0324** [comment]
@breakworldly 多谢反馈
